CC = 	gcc -Wall -O2 -I.
RM = 	rm -rf

all: chess_general1 chess_general2

chess_general1: chess_general1.o
chess_general1.o: chess_general1.c 

chess_general2: chess_general2.o
chess_general2.o: chess_general2.c

clean:
	$(RM) *.o 
