CC = gcc -Wall -O2 -I.
RM = rm -rf

all: atoi atoi2 atoi3 atof atol strtod strtol strtoul



atoi: atoi.o
atoi.o:atoi.c

atoi2: atoi2.o
atoi2.o:atoi2.c

atoi3: atoi3.o
atoi3.o:atoi3.c

atof: atof.o
atof.o: atof.c

atol: atol.o
atol.o: atol.c

strtod: strtod.o
strtod.o:strtod.c

strtol:strtol.o
strtol.o:strtol.c

strtoul:strtoul.o
strtoul.o:strtoul.c


clean:
	$(RM) *.o
