
timer: timer_poll.o main.o
	g++ timer_poll.o main.o -o timer

timer_poll.o: timer_poll.cpp timer_poll.h
p
p
p
p
p
	g++ timer_poll.cpp timer_poll.h -c timer_poll.o

main.o: main.cpp
	g++ main.cpp -c main.o
