CC =	gcc -Wall -O2 -I.
RM =	rm -rf

all: pointer_and_array1 pointer_and_array2

pointer_and_array1: pointer_and_array1.o
pointer_and_array1.o: pointer_and_array1.c

pointer_and_array2: pointer_and_array2.o
pointer_and_array2.o: pointer_and_array2.c

clean:
	$(RM)  *.o
