CC = gcc -Wall -O2 -I.
RM = rm -rf 

all: pid_ppid_uid_euid_gid_egid

pid_ppid_uid_euid_gid_egid: pid_ppid_uid_euid_gid_egid.o
pid_ppid_uid_euid_gid_egid.o: pid_ppid_uid_euid_gid_egid.c 

clean:
	$(RM) *.o 
